spring.application.name=simple-mcp-client
server.port=8040
# Global timeout for any controller method returning CompletableFuture/Callable
spring.mvc.async.request-timeout=300000
# Spring AI OpenAI Configuration
spring.ai.mistralai.api-key=${MISTRALAI_API_KEY}
# Optional: Specify the model (default is mistral-small-latest)
spring.ai.mistralai.chat.options.model=mistral-large-latest
spring.ai.mcp.client.enabled=true

spring.ai.mcp.client.transport.protocol=STREAMABLE
spring.ai.mcp.client.type=SYNC

spring.ai.mcp.client.streamable-http.connections.iie-chatbot.url=http://localhost:8080
# Set the timeout for all MCP client requests (e.g., to 5 minutes)
spring.ai.mcp.client.request-timeout=300s
spring.ai.mcp.client.capabilities.elicitation={}
logging.level.io.modelcontextprotocol.client=TRACE
logging.level.io.modelcontextprotocol.spec=INFO
logging.level.org.springframework.ai.mcp=TRACE
logging.level.org.springframework.ai.mcp.client=TRACE


