spring.application.name=simple-mcp-client
server.port=8040

# Spring AI OpenAI Configuration
spring.ai.mistralai.api-key=00LleM6p8YWPK1GMSDpWFLrNQKT5y4Ki
# Optional: Specify the model (default is mistral-small-latest)
spring.ai.mistralai.chat.options.model=mistral-large-latest
spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.request-timeout=5m
spring.ai.mcp.client.transport.protocol=STREAMABLE
spring.ai.mcp.client.type=SYNC

spring.ai.mcp.client.streamable-http.connections.spring-ai-mcp-one.url=http://localhost:8080

spring.ai.mcp.client.capabilities.elicitation={}
logging.level.io.modelcontextprotocol.client=TRACE
logging.level.io.modelcontextprotocol.spec=INFO
logging.level.org.springframework.ai.mcp=TRACE
logging.level.org.springframework.ai.mcp.client=TRACE