spring.application.name=simple-mcp-client
server.port=8040

# Spring AI OpenAI Configuration
spring.ai.openai.base-url=http://localhost:1234
spring.ai.openai.api-key=""
spring.ai.openai.chat.options.model=qwen/qwen3-vl-4b

spring.ai.mcp.client.request-timeout=5m
spring.ai.mcp.client.streamable-http.connections.ticketing-tool-streamable-v5-with-progress.url=http://localhost:8080
spring.ai.mcp.client.capabilities.elicitation=true
logging.level.io.modelcontextprotocol.client=INFO
logging.level.io.modelcontextprotocol.spec=INFO